############################
## CHANGE THESE
############################

baseURL: "https://Shamik-07.github.io/"
title: My New Hugo Site

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-uk"
enableRobotsTXT: true
markup:
  goldmark:
    renderHooks:
      image:
        enableDefault: true
      link:
        enableDefault: true
        